#!/bin/bash

configFile=$1
usageError="n"

      #****   		EDIT PATH IN NEXT LINE	 	****
autoprintBaseDir="/home/user/AutPrintMailAttachments/workdir"

tmpMailFile=""
tmpMailPrintFolder=""
tmpRenderedMailPrintFolder=""

#loggingfunction
DATE='date +%Y/%m/%d:%H:%M:%S'
LOGGING_PREFIX=' autoprint-logging:'
function write_log {
   LOGMSG=$(echo `$DATE`"$LOGGING_PREFIX $1")
   logger -p local7.info "$LOGMSG"
}

printUsage(){
     echo "# Error with config file, usage ./script config.cfg
     exit 1
}
processMail(){
       IFS=' ' read mailServer servertype ssl mailAddress passwd printServer printQueue attachmentTypes copies keepOnServer imapfolder <<< "$configLine"
       echo "set no syslog" > "$fetchmailrc"
      
      #****   		EDIT PATH IN NEXT LINE	 	****
       echo "set logfile /home/user/AutPrintMailAttachments/workdir/logfile.log" >> "$fetchmailrc"
    
    echo "poll $mailServer " >> "$fetchmailrc"
      if [[ $servertype == "pop3" ]]; then 
         echo "  proto  pop3" >> "$fetchmailrc"
       else
         echo "  proto  imap" >> "$fetchmailrc" >> "$fetchmailrc"
       fi
              if [[ $ssl == "N" ]]; then 
         echo ""
       else
         echo "  ssl" >> "$fetchmailrc"
       fi
       echo " user $mailAddress   pass $passwd " >> "$fetchmailrc"
       if [[ $imapfolder == "" ]]; then 
         echo ""
       else
         echo "    folder $imapfolder" >> "$fetchmailrc"
       fi 
       cp "$fetchmailrc" /tmp/tomFetchmailrc
       if [[ $keepOnServer == "Y" ]]; then 
		/usr/bin/fetchmail -f "$fetchmailrc" --keep --bsmtp "$tmpMailFile"
       else
		/usr/bin/fetchmail -f "$fetchmailrc" --bsmtp "$tmpMailFile"
       fi
     #  echo "tmpMailFile: $tmpMailFile" 
     #  echo "tmpRenderedMailPrintFolder: $tmpRenderedMailPrintFolder"
      /usr/bin/uudeview -a +e $attachmentTypes -p $tmpMailPrintFolder  -i $tmpMailFile
      cd "$tmpMailPrintFolder" 
     #for file in *; do mv "$file" `echo $file | tr ' ' '_'` ; done
     for f in *; do
        if [[ $f == "*"  ]];then 
           echo ""
           echo " ..this is a not done correct: $f"
        else
          nfile=$(echo $f | tr ' ' '_')
          if [[ "$f" == "$nfile" ]];then 
                echo ""
          else
		mv "$f" "$nfile" 
          fi
           #echo "....this is done correctly: $f"
           #ltrim
           f=$(echo $nfile | sed 's/^[ \t]*//')
           #rtrim
           f=$(echo $f | sed -e 's/[ \t]*$//')
           if [[ $f == "" ]];then
                echo ""
           else
           	counter=1
                if [ $copies -gt 10 ];then 
                    copies=10
                fi

		renderedFile=$( echo "$tmpRenderedMailPrintFolder/$f.autoprint.ps" )
                #echo "renderedFile is placed here: $renderedFile"
	        pdftops -paper A4 "$f" "$renderedFile"
                until [ $counter -gt $copies ] 
                do 
	             lpr -H"$printServer" -P"$printQueue" "$renderedFile"
                    if [ $counter -eq 1 ]; then 
			write_log "lpr -H$printServer -P$printQueue $renderedFile (orgFile: $f   copies: $copies )"
		    fi
                    #lpr -H"$printServer" -P"$printQueue" "$f" 
                    counter=$[$counter+1]
                done
	   fi
        fi
     done




}




### start main script 
if [ $# -lt 1 ]; then 
  usageError="X"
fi
if [[ $usageError == "X" ]];then
   printUsage
fi  
if [ -f "$configFile" ]; then 
    echo ""
else
    echo "#################################################"
    echo "  config file $configFile  not found"
    echo ""
    printUsage
fi 

while read LINE ; do
       configLine=$LINE
       configLine=$(echo $configLine | sed 's/^[ \t]*//')
       configLine=$(echo $configLine | sed 's/^[;:]/#/')
       if [[ $configLine != "#"* ]];then
         fetchmailrc=$(mktemp)
         tmpMailFile=$(mktemp  -p "$autoprintBaseDir" -t "mailFilE"__XXXXXXXXXX)
         tmpMailPrintFolder=$(mktemp -d -p "$autoprintBaseDir" -t "mailPrintFolder"__XXXXXXXXXX)
         tmpRenderedMailPrintFolder=$(mktemp -d -p "$autoprintBaseDir" -t "renderedMailFolder"__XXXXXXXXXX)
         echo "processing: $configLine"
         processMail
	 rm -f "$fetchmailrc"
         if [[ $tmpMailFile == "$autoprintBaseDir"* ]]; then 
             rm -f "$tmpMailFile" 
      	 fi 
         if [[ $tmpMailPrintFolder == "$autoprintBaseDir"* ]]; then 
         #     echo "tmp folder will be deleted now"
		rm -Rf "$tmpMailPrintFolder" 
      	 fi 
         if [[ $tmpRenderedMailPrintFolder == "$autoprintBaseDir"* ]]; then 
         #     echo "tmp folder will be deleted now"
                ls -la  "$tmpRenderedMailPrintFolder"    >> /tmp/tom.render
		rm -Rf "$tmpRenderedMailPrintFolder"
      	 fi 
	fi 
done <$configFile

